### ISSUE TITLE
投票后投票统计信息没有更新

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#1]
## 步骤
  【合伙人】页面点击投票后，投票成功，没有更新投票信息。
## 期望
更新投票信息

**Comment by vjoke** [comment]
如果交易成功， 直接增加runtime.vote_count 即可。不需要API 去获取

**Comment by canfoo** [comment]
done v0.02

**Comment by eosdex** [comment]
投完票按钮没置灰 @canfoo
