### ISSUE TITLE
调整订单类型选择列表位置

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#10]
## 步骤
选择市价单、限价单时弹出列表在底部
## 期望
希望居中显示弹出框。 另外语言选择弹出框也请居中显示，方便操作

**Comment by canfoo** [comment]
done v0.02

**Comment by eosdex** [comment]
我看到newdex是这样的， 对用户来讲比较好操作。 我的Android手机显示最下面， 从上面点击选择订单，手指要挪到最底部来操作，比较不方便。 
![image](https://user-images.githubusercontent.com/44268601/49089349-57643000-f296-11e8-8604-7832f224c3f1.png)

**Comment by canfoo** [comment]
done v1.03
