### ISSUE TITLE
错误代码显示在前端

### ISSUE THREAD

**Issue by sheeknows** [eosdex/awesome#15]
### 改进为正确提示信息。

**Comment by eosdex** [comment]
请确认一下错误信息err_no_idle_orders 还是err-no-idle-orders？ @sheeknows

**Comment by sheeknows** [comment]
![image](https://user-images.githubusercontent.com/26454510/49088836-19b2d780-f295-11e8-9004-8f42176bf63b.png)
已确认是err_no_idle_orders
