### ISSUE TITLE
我的RTC 页面交互逻辑问题

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#16]
## 步骤
[我的RTC] 页面

## 期望
1. ~~无refund资产时不需显示refund 小方框~~
1. 点击{我的交易所} 下面的交易对， 可以跳转到对应交易对， 注意stopPropgation
1. {已激活} 子页面 列表标题 第二列 应为"分红池" lang key 为 "dividend_pool"
1. staked 没有精度
1. ~~投票后，没有置灰色按钮。~~
1. ~~待激活却显示可领取分红，疑似后台刷新数据导致~~
![image](https://user-images.githubusercontent.com/44268601/49082187-182ce380-f284-11e8-9d16-87d2b92222db.png)

**Comment by eosdex** [comment]
1. {已激活} 子页面 列表标题 第二列 应为"分红池" lang key 为 "dividend_pool"， 标题是分红池，下面还是累计分红 "sum_of_dividend" 
1. staked 没有精度

**Comment by canfoo** [comment]
done v0.04
