### ISSUE TITLE
成交量单位显示有误

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#17]
## 步骤
【交易】页面， 当前委托列表中，委托量和成交量的单位显示不正确
## 期望
委托量取 order.initial 的单位； 成交量取order.deal 的单位。
![image](https://user-images.githubusercontent.com/44268601/49083347-4829b600-f287-11e8-9ead-49697c94bc23.png)

**Comment by canfoo** [comment]
done v0.0.4

**Comment by eosdex** [comment]
正确显示TOKEN的Name, 以AAA/EOS 交易举例如下：
## AAA/EOS 卖单
- 委托价单位为EOS
- 委托量单位为AAA
- 成交量单位为EOS， 表示卖AAA已获得多少EOS

## AAA/EOS 买单
- 委托价单位为EOS
- 委托量单位为EOS
- 成交量单位为AAA， 表示已买了多少AAA

**Comment by canfoo** [comment]
done v0.0.5
