### ISSUE TITLE
增大滑块的thumb

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#34]
## 步骤
【滑块】 的thumb

## 期望
![image](https://user-images.githubusercontent.com/44268601/49339231-d0ce9a80-f669-11e8-8817-3fe16eea59eb.png)
适当把所有thumb 再增大一点， 方便操作

**Comment by canfoo** [comment]
done v1.03

**Comment by eosdex** [comment]
我的手指终于可以很灵活的拖动了 ：）
