### ISSUE TITLE
合伙人中 “总抵押” 颜色要调整一下

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#35]
## 步骤
【合伙人】页面

## 期望
“总抵押” 字体颜色设置为和上面的“分红池" 一样的颜色。
![image](https://user-images.githubusercontent.com/44268601/49339341-0c1d9900-f66b-11e8-80d2-0dd2d4d01eb7.png)

**Comment by canfoo** [comment]
done v1.03
