### ISSUE TITLE
卖出RTC 计算错误

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#37]
## 步骤
【我的RTC】页面， 卖出RTC， 拖动滑块， 显示的可兑换的EOS数量有误
![image](https://user-images.githubusercontent.com/44268601/49346866-52a6de00-f6d3-11e8-8220-bf410e7e954d.png)
## 期望
正确显示, 计算过程为：
1. 获取RTC market数据
```
{
  "rows": [{
      "supply": "10000000000.0000 RTCCORE",
      "base": {
        "balance": "999721359.3942 RTC",
        "weight": "0.50000000000000000"
      },
      "quote": {
        "balance": "10002787.1871 EOS",
        "weight": "0.50000000000000000"
      }
    }
  ],
  "more": false
}
```
得到 B = 10002787.1871
C = 999721359.3942
则可兑换的RTC 为 rtc_amount / C * B * (1-0.5%)

**Comment by canfoo** [comment]
done v0.0.5
