### ISSUE TITLE
【订单】页面搜索结果被自动刷新

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#39]
## 步骤
【订单】页面搜索结果被自动刷新

## 期望
结果不被自动刷新； 另外当搜索条件不为空时，搜索icon改变下状态，比如显示为实心的icon，以示区别。
![image](https://user-images.githubusercontent.com/44268601/49380850-9b02e200-f74d-11e8-9cb8-86e9e09a711e.png)

**Comment by eosdex** [comment]
最好能做成下拉刷新，后台就不用刷了，这样处理逻辑简单， 还是要辛苦你一下。

**Comment by canfoo** [comment]
done v0.08

**Comment by eosdex** [comment]
well done
