### ISSUE TITLE
未实现项目介绍子页面

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#4]
## 步骤
【订单】页面中，当前订单右边还有个subpage， 显示当前项目介绍比如ABC/EOS， 需要显示ABC的信息。

## 期望
增加【项目介绍子页面】， 内容可复用【交易对】页面介绍部分。项目介绍内容一般不会变化，可加载一次后本地缓存，方便快速提取。

**Comment by canfoo** [comment]
done v0.02
