### ISSUE TITLE
【交易对】页面滚动信息有重复

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#40]
## 步骤
在BBB/EOS 【交易对】页面，滚动显示2条信息一模一样。而数据只有1条。

![image](https://user-images.githubusercontent.com/44268601/49382149-9a1f7f80-f750-11e8-89b1-13c372332bdb.png)

![image](https://user-images.githubusercontent.com/44268601/49382092-70665880-f750-11e8-9cae-80323a108a61.png)

## 期望
不重复显示

**Comment by canfoo** [comment]
done v0.08
