### ISSUE TITLE
【交易】页面无法挂市价卖单

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#41]
## 步骤
【交易】页面
当前价格为0.004100， 委托1000.810， 提示必须 > 0.1 EOS
![image](https://user-images.githubusercontent.com/44268601/49383747-6ba3a380-f754-11e8-8a25-f59c7ac49cb3.png)

## 期望
比如BBB/EOS 交易对
当24H 最低价不为0时，用(current_price * amount) > 0.1 做条件判断; 否则只要amount >= 1.000 BBB 即可。

**Comment by canfoo** [comment]
done v0.08
