### ISSUE TITLE
【交易】页面挂 市价 买单， 结果显示在卖单中

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#42]
## 步骤
【交易】页面挂 市价 买单， 结果显示在卖单中。

![image](https://user-images.githubusercontent.com/44268601/49385551-ab6c8a00-f758-11e8-9509-6cd66c1be847.png)
合约里无数据：
![image](https://user-images.githubusercontent.com/44268601/49385625-d2c35700-f758-11e8-8ac9-3430f6c8ee26.png)

## 期望
买单不能显示在卖单列表中。

**Comment by canfoo** [comment]
done v0.09

**Comment by eosdex** [comment]
暂时替换upper_bound最低字节为FF
