### ISSUE TITLE
【交易】页面买入BBB，撮合成功，切换到卖出显示BBB 余额为0

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#44]
## 步骤
【交易】页面买入BBB， 撮合成功， 马上切换到卖出界面， 显示BBB余额为0， 不能下卖单。
![image](https://user-images.githubusercontent.com/44268601/49408659-21dcac80-f798-11e8-920f-897b7035d33e.png)

## 期望
买入、卖出挂单成功后刷新余额， 下拉刷新【交易】界面

**Comment by canfoo** [comment]
done v0.08
