### ISSUE TITLE
【交易对】页面界面逻辑问题

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#49]
## 步骤
用户fff333333333 在AAA/EOS 交易对抵押2000.0000 RTC， 排第三位。饼图没更新

![image](https://user-images.githubusercontent.com/44268601/49409786-13dd5a80-f79d-11e8-87be-ecb8ede868e8.png)
另外再次进入该界面后，发现， 显示未生效抵押为4000.0000 RTC。
![image](https://user-images.githubusercontent.com/44268601/49409888-79314b80-f79d-11e8-8c5b-4479e1b42fcd.png)
数据显示是2000.0000 RTC
![image](https://user-images.githubusercontent.com/44268601/49410205-cd88fb00-f79e-11e8-89e9-b486202e5d22.png)

## 期望
改成下拉刷新
正确显示数据

**Comment by canfoo** [comment]
done v0.08

**Comment by canfoo** [comment]
done v0.09
