### ISSUE TITLE
【行情】页面在搜索框下拉后卡住

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#50]
## 步骤
【行情】页面搜索框，输入ABC， 下拉刷新，一直显示loading
![image](https://user-images.githubusercontent.com/44268601/49480248-ed80f300-f860-11e8-8cc3-422f980486ff.png)

## 期望
不卡住

**Comment by eosdex** [comment]
多试了几次，偶尔会卡住。 
另外， 搜索框 【取消】后界面应显示所有交易对。

**Comment by eosdex** [comment]
另外，在【行情】 下拉， 偶尔也会卡住， 貌似拉取不导数据导致的， 能否设置timeout时间， 做成一个可配置参数。 先默认为10秒。 
![image](https://user-images.githubusercontent.com/44268601/49480590-3f764880-f862-11e8-8458-1931e99cfc92.png)

**Comment by eosdex** [comment]
一旦卡住， 在meetone就无法再打开了， refresh页面也不行。 必须退出整个app，再进入才行

**Comment by canfoo** [comment]
loading timeout 设置成10s  done v0.09
