### ISSUE TITLE
【交易】页面市价买入金额不显示

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#51]
## 步骤
【交易】页面 DDD/EOS， 选择市价买， 拖动slider， slider左上方的可用一直显示为0， 无法知道下单
的具体金额。
![image](https://user-images.githubusercontent.com/44268601/49481043-11920380-f864-11e8-845e-0e0bce0fdf46.png)

## 期望
显示下单的EOS 金额。 市价买单 直接显示（当前EOS余额）* slider_percent.

**Comment by canfoo** [comment]
done v0.09

**Comment by eosdex** [comment]
市价买入， 拖动slider 下单金额不变化。 
![image](https://user-images.githubusercontent.com/44268601/49552124-2be3e400-f92d-11e8-94e8-f802c641a70b.png)
