### ISSUE TITLE
【交易】页面卖出所有AAA后，AAA 余额不变，下拉也不刷新。

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#53]
## 步骤
【交易】页面卖出所有AAA后，AAA 余额不变，下拉也不刷新。
![image](https://user-images.githubusercontent.com/44268601/49481592-849c7980-f866-11e8-80e5-4ba892a641c6.png)

## 期望
刷新数据

**Comment by canfoo** [comment]
done v0.09
