### ISSUE TITLE
【更多】页面中的 “问题反馈”显示不完整

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#57]
## 步骤
【更多】页面中的 
![image](https://user-images.githubusercontent.com/44268601/49552523-f9d38180-f92e-11e8-80c7-97241100a0fe.png)

## 期望
正常显示

**Comment by canfoo** [comment]
done v0.10 (有些屏幕高度比较小导致的，现在加深底部margin，往上拉就可以看到了)

**Comment by eosdex** [comment]
ok
