### ISSUE TITLE
【首页】底部增加 MYDEX copyrights 等信息

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#59]
## 期望
增加3行， 居中显示
Email: myeosdex@gmail.com
Telegram: xxxx
Copyright © 2018 MYDEX Inc. All rights reserved.
类似NEWDEX
![image](https://user-images.githubusercontent.com/44268601/49553131-33a58780-f931-11e8-97a9-7a2e5375e9ad.png)

**Comment by canfoo** [comment]
done v0.10
