### ISSUE TITLE
委托量标题错误， 显示委托量KKK

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#6]
## 步骤
【订单】页面中，委托量标题错误, 显示为 委托量(kkk)
## 期望
正确显示TOKEN的Name， 比如AAA/EOS 卖单， 委托量单位为AAA;  AAA/EOS 买单，委托量单位为EOS

**Comment by canfoo** [comment]
done v0.02

**Comment by eosdex** [comment]
#17 有具体说明 @canfoo
