### ISSUE TITLE
交易页面中显示时间详细信息

### ISSUE THREAD

**Issue by eosdex** [eosdex/awesome#9]
## 步骤
 【交易页面】 中当前委托列表未显示详细时间。

## 期望
显示时间格式 MM-DD HH:MM:SS， 例如 "11-27 08:30:29" , 可去掉时间字段左边的交易对名称，因为在该交易对的交易页面，这个交易对字段都是一样的。另外当前委托页面整个列表布局偏右，可居中

**Comment by canfoo** [comment]
done v0.02
